### ISSUE TITLE
Android App is not working

### ISSUE THREAD

**Issue by norbert-walter** [volkszaehler/app-android#13]
The Android App is on my mobile phone not working. I using a Wiko Darknight and a old version (V0.2) and connect the App with my Volkszaehler. Under settings URL I using this string:

http://192.168.1.12/volkszaehler.org/htdocs/middleware.php

Volkszaehler is on my system not in the http root folder installedn (but only in a subfolder).

I can reload all channels and get a error message. I see that the App has downloaded all channels but I get a error message. Wat for a Volkszahler version I need? Is the version 0.2 ok or I need a actual download from Github?

**Comment by SirkoVZ** [comment]
I don't know whether the old version can be the reason... Maybe it's worth a try to update it.

However, please tell me exactly when the error occurs (after you clicked what...) and what error is shown.

Regards
Sirko

**Comment by norbert-walter** [comment]
I checked the actual version number. Actual is V 0.5. I using V 0.2. Witch version using you with the App? When I read all channels (push on read channels) then poppup a window. The window name is Fehler with al long list. The list is the answare from the middle ware with all channel data. I cold not find any error codes.

If you wand I can give you a remote account to my system via internet. Then you can self check the situation. Is it helpfully for you? I dont usind username and passwort.

Regards
Norbert

**Comment by andig** [comment]
Ich denke Deine middleware url ist falsch. Funktioniert die denn wenn Du sie im Browser eingibst?

Viele Grüße,
Andreas

**Comment by SirkoVZ** [comment]
Do you prefer english? If so, please let me know.

Wenn es eine lange Liste ist, dann könnte meine Erkennung der vermeintlich (nicht) korrekten Antwort nicht passen. Wie fängt denn die Ergebnisliste an?
So wahrscheinlich nicht: "version":"0.3","data"

Grüße
Sirko

**Comment by norbert-walter** [comment]
Hi, meine Liste fängt mit "version":"0.2","data" an. Ist also die V0.2 für VZ. Haben sich die Bezeichner für die Kanäle in der json-Antwort von V0.2 auf V0.3 geändert? Dann wäre es wohl gut, bevor die App Daten liest die Version auszuwerten und dann ggf. eine Meldung auszugeben, dass die Version nicht passt. Unter volkszaehler.org habe ich angeregt, die Versionsnummer in der Startseite direkt anzuzeigen.

Die V0.2 ist ziemlich breit in Benutzung, da sie lange Zeit die einzige stabile Version war. Ich würde ungern meine ganzen Daten nach V0.3 portieren wollen, da ich über fast 3 Jahre Aufzeichnungen gemacht habe. Zudem hat sich vermutlich auch das Datenbankformat geändert, so dass es extrem aufwändig ist die Daten zu portieren. Es wäre schön, wenn die App auch mit der V0.2 klarkommt.

Würde es Dir helfen, wenn ich Dir den Zugang zu meinem VZ per Internet freischalte?

Vielen Dank für Deine Hilfe und die viele Arbeit für die App

Norbert

**Comment by andig** [comment]
> meine Liste fängt mit "version":"0.2","data" an

@norbert-walter das ist steinalt- bitte aktualisieren.

> Wenn es eine lange Liste ist, dann könnte meine Erkennung der vermeintlich (nicht) korrekten Antwort nicht passen. Wie fängt denn die Ergebnisliste an?

@SirkoVZ was meinst Du damit- machst Du String parsing? Richtig wäre das JSON mit einer geeigneten Bibliothek zu parsen?

**Comment by SirkoVZ** [comment]
ja, ich prüfe erstmal, ob JSON-Daten kommen und mache dann ein JSON-objekt draus, welches ich verarbeiten kann.
Manchmal kommen auch keine JSON-Antworten, z.B. wenn es Verbindungsprobleme gibt oder ähnliches.
Hier erstmal eine Version für Norbert, die sollte gehen. Ich akzeptiere einfach zusätzlich 0.2 Versionen. Ich laß mir aber noch was besseres einfallen...
[vz_app_Norbert_Walter.zip](https://github.com/volkszaehler/app-android/files/461196/vz_app_Norbert_Walter.zip)

**Comment by andig** [comment]
> Ich laß mir aber noch was besseres einfallen...

Die Middleware tut einfach so als wäre es JSON, parst also. Wenns kein JSON ist gibts eien Exception die abgefangen wird. Der Stringverlgleich ist wirklich nicht stabil. Und gut wäre die Version auf >=0.3 zu prüfen. M.E. sollten 0.2er User zum Upgrade überedet werden, das ist wirklich aus der Steinzeit...

**Comment by norbert-walter** [comment]
Wenn ich update wie bekomme ich meine Daten transferiert? Bleibt das Datenbankschema gleich und ich brauche nur den PHP-Teil aktualisieren? Dann wäre das kein Problem. Ich würde aber ungern meine letzten 3 Jahre gw. Import- / Updateproblemen verliegen wollen.

**Comment by norbert-walter** [comment]
@SirkoVZ Ich probiere die neue Version gleich mal aus und berichte dann. Vielen Dank für Deine Bemühungen.

**Comment by norbert-walter** [comment]
@SirkoVZ App funktioniert jetzt. Echt klasse! Jetzt kann ich endlich mal von unterwegs problemlos und zügig auf VZ zugreifen. Vielen, vielen Dank! :-)

So wie ich das sehe kann man nur öffentliche Kanäle zur Anzeige bringen. Könnte man auch UUIDs händisch eingeben? Dann könnte man auch die nicht öffentlichen Kanäle anzeigen. Das wäre praktisch, da ich nicht öffentliche Kanäle zu Diagnosezwecken verwende, die ich auch ansehen möchte. Das sind bei mir z.B. Schaltausgänge von Logikverknüpfungen für eine Wärmepumpe die ich logge.

**Comment by SirkoVZ** [comment]
Hi Norbert,

hier ist eine überarbeitete Version, welche auch version 0.2 (u.a.) können sollte und ein manuelles Hinzufügen der privaten UUIDs unterstützt.
Bitte teste die mal, danke
Grüße
Sirko

PS: Leider lassen sich heut keine .zips hochladen, lade das .apk mal bitte hier runter:
http://workupload.com/file/HMcGerK

**Comment by norbert-walter** [comment]
Hi Sirco,
hab es gerade ausprobiert. Klappt prima! Vielen Dank für die Änderung.

Wäre es möglich die Farben für die Werte aus der Datenbank zu lesen und die selben zu verwenden? Könnte man zudem alle ausgewählten Werte in einem Diagram darstellen? Dann wäre es so wie auf der Webseite. Man sollte mindestens 2 Werte gleichzeitig im Diagramm anzeigen können mit eigenen Achsen (links und rechts), damit man abhängige Werte kontrollieren kann (z.B. Temperatur und Leistungsaufnahme). Bei mehreren Werten als 2 wird es mit den Achsen kompliziert. An welche Achse soll man die Werte anbinden? Teilweise leidet dann die Lesbarkeit. Das ist aber auch ein Problem in der Webversion. Wäre toll, wenn das auch ginge.

Ich bin hier nur am wünschen ohne das ich was beitragen kann. Werde gerne alles testen, wenn es was neues gibt. Also nochmal großes Lob für dein Engagement.

Norbert

**Comment by andig** [comment]
Für die Achsen hat das Frontend einen einfachen Algorithmus: gleiche Einheiten auf gleiche Axen es sei denn eine abweichende Achse ist manuell konfiguriert. Jede neue Einheit kommt auf eine zusätzliche Achse rechts.

Viele Grüße, Andreas

**Comment by norbert-walter** [comment]
Ist dann nur die Frage wie ich 10 verschiedene Werte anzeigen kann die u.U. 5 unterschidliche Einheiten haben (Temp, Druck, Feuchte, Solare Einstarhlung, Strom, Gas, Wasser). Dann wird es schnell unübersichtlich im Diagramm bei vielen Achsen und kleinem Display. Im VZ Vers. 0.2 gab es nur 2 Achsen ohne Einheiten. Eine für kleine Werte und eine für große Werte. Ja nachdem wo die Werte besser passen wurde dann die entsprechende Achse gewählt. Das war ganz ok bis auf die Luftdruckwerte, da sie zw. 995 und 1040 schwanken können. Die wurden meistens an die große Achse angebunden mit dem Nachteil, dass nur eine wagerechte Linie zu sehen war. In Sikos App kann man die Achsen auch ohne Nullbezug plotten lassen. Das finde ich gut. Dann orientiert sich die Achsenskalierung an den Min- und Max-Werten. Ich denke 2 Achsenlegenden (links und rechts) sollten für die App ausreichen. Wer mehr Details sehen will kann die Werte ja einzeln plotten.

**Comment by andig** [comment]
Hallo Norbert,

> On 15 Sep 2016, at 11:52, norbert-walter <notifications@github.com> wrote:
> 
> Ist dann nur die Frage wie ich 10 verschiedene Werte anzeigen kann die u.U. 5 unterschidliche Einheiten haben (Temp, Druck, Feuchte, Solare Einstarhlung, Strom, Gas, Wasser). Dann wird es schnell unübersichtlich im Diagramm bei vielen Achsen und kleinem Display. Im VZ Vers. 0.2 gab es nur 2 Achsen ohne Einheiten. Eine für kleine Werte und eine für große Werte.
> 

Ja, früher war alles besser ;) Da schöne ist: jetzt geht mehr und Du kannst Dir das alte Verhalten immer noch konfigurieren.
> Ja nachdem wo die Werte besser passen wurde dann die entsprechende Achse gewählt. Das war ganz ok bis auf die Luftdruckwerte, da sie zw. 995 und 1040 schwanken können. Die wurden meistens an die große Achse angebunden mit dem Nachteil, dass nur eine wagerechte Linie zu sehen war.
> 
Leg einfach jeden Kanal auf die Achse die Du haben möchtest- im Frontend lassen sich 1 (links) bis 4 (2-4 rehts) einstellen.
> In Sikos App kann man die Achsen auch ohne Nullbezug plotten lassen. Das finde ich gut.
> 
Gehe in die options.js und trage einfach bei Deiner Wunschachse ein min:800 oder Ähnliches für den Luftdruck ein und lege Luftdruck auf diese Achse. 
> Dann orientiert sich die Achsenskalierung an den Min- und Max-Werten. Ich denke 2 Achsenlegenden (links und rechts) sollten für die App ausreichen. Wer mehr Details sehen will kann die Werte ja einzeln plotten.
> 
> 

Prinzipiell “howto” Diskussionen bitte auf die Mailingliste- in jedem Fall solltest Du das gewünschte Verhalten damit hinbekommen.

Viele Grüße, Andreas

**Comment by norbert-walter** [comment]
Werde das mal in der neuen Version ausprobieren mit den Achsen. Ich quäle mich aktuell fürchterlich ab, auf die neue VZ-Version zu aktualisieren. Die Installations-Scripte benötigen zwingend PHP > 5.4.  Das geht aber unter Ubuntu 11.04 (mein altes laufendes System) nicht mehr. PHP zu aktualisieren ist auch nicht ohne. Wenn ich die VZ-Version 0.2 auschecke, dann kann ich sie auch nicht mehr installieren, da der Composer immer in der aktuellen Version geladen wird und dann an der PHP-Version scheitert. Ich muss dann also auch Ubuntu updaten. Aber schön zu wissen, dass man die Achsen individuell einstellen kann.

**Comment by andig** [comment]
Hilfe zum Upgrade gerne auf der ML.

**Comment by SirkoVZ** [comment]
noch offene Punkre:
-  Farben für die Werte aus der Datenbank zu lesen und die selben zu verwenden  
das geht normalerweise bereits, zumindest mit 0.3 oder höher (denke ich)
- Könnte man zudem alle ausgewählten Werte in einem Diagram darstellen  
auch das geht, "long touch" im Chart sollte die anzuzeigenden Channels zeigen
- mehrere y-Achsen  
ich werd mal sehen, was ich tun kann...
