### ISSUE TITLE
Zeitachse Option 12/24 h

### ISSUE THREAD

**Issue by TylonHH** [volkszaehler/app-android#15]
Hi,
Wie wäre es mit einer einstellbaren Zeitachse für die Uhr in 12 Stunden (6:10pm) oder 24 Stunden (18:10 Uhr) Format?

**Comment by SirkoVZ** [comment]
das geschieht eigentlich automatisch: bei einem deutsch eingestellten gerät gibt es 24h, bei englisch (oder sonstigen Sprachen=Fallback auf englisch) gibt es 12h mit am/pm

**Comment by SirkoVZ** [comment]
dein Screenshot bei https://github.com/volkszaehler/app-android/issues/16 zeigt die Uhrzeit mit "vorm.", also "am", aber in deutsch. Hast du irgendwelche "gemischten" Einstellungen gesetzt?
Ich hätte erwartet, daß man wenn man deutsch einstellt, automatisch 24h Zeitformat gesetzt wird...

**Comment by TylonHH** [comment]
Also meins ist deutsch.
Welcher Wert wird denn zur Ermittlung der Sprache verwendet? Kann ich diese Eigenschaft irgendwie ermitteln/auslesen?

**Comment by SirkoVZ** [comment]
Dsa geschieht alles Android-intern. Man muß der app nur eine de-Datei mit deutschen Strings geben, dann ist die app lokalisiert.
Ich dachte eher, daß dein Honor auf deutsch gestellt ist und die Uhrzeit auf am/pm.
Allerdings konnte ich das auf meinem Samsung nicht nachstellen, die App hat immer 24h angezeigt, während die Uhr im Hadny oben rechts pm meinte. In deinem Screenshot ist aber kein am oben bei der Uhrzeit zu sehen...

**Comment by TylonHH** [comment]
Mein Screenshot aus #16 wurde morgens gemacht 😉

Also mein Handy ist komplett auf Deutsch eingestellt, vom Menü bis zur Uhr.

Ich habe nochmal ein Screenshot am Nachmittag gemacht. Demnach wird eine 12 Stunden Anzeige in Deutsch angezeigt ("nachm.")
![screenshot_2016-09-29-15-33-08](https://cloud.githubusercontent.com/assets/18073299/18956131/9c649230-865a-11e6-91b0-dc1eeed33133.png)

**Comment by SirkoVZ** [comment]
Hmm, laut hier:
https://code.google.com/p/android/issues/detail?id=181201#c7
kommt eine deutsche am/pm Übersetzung, wenn die Locale deutsch ist, aber die Uhr auf 12h eingestellt ist.
Kannst du das nochmal prüfen, ggfs. mal ein bischen hin- und herstellen?

**Comment by TylonHH** [comment]
Das war's. Ich habe auf'm Handy die aktivierte "24 Stunden Anzeige verwenden" deaktiviert und wieder aktiviert. Jetzt wird es richtig angezeigt.

**Comment by SirkoVZ** [comment]
jo, steht auch hier sehe ich grad:
https://code.google.com/p/android/issues/detail?id=181201#c17
