### ISSUE TITLE
anpassen der Schriftgröße

### ISSUE THREAD

**Issue by TylonHH** [volkszaehler/app-android#16]
Hi,
Ist die Schriftgröße dynamisch oder hard coded?
Bei meinen Honor 7 erscheint die Schrift recht groß und einzelne Buchstaben werden umgebrochen.
![img_20160927_050818](https://cloud.githubusercontent.com/assets/18073299/18858983/70aaeaa4-8470-11e6-9d33-bcca8e87690a.png)

**Comment by SirkoVZ** [comment]
eigentlich dynamisch, ich hab's in der nächsten Version mal ne Nummer kleiner gemacht, mal sehen...
