### ISSUE TITLE
Error nach Umzug der middleware

### ISSUE THREAD

**Issue by TylonHH** [volkszaehler/app-android#17]
Hi,
Ich musste mit der middleware umziehen und nutze nun den Port 81. `http://192.168.178.22:81/middleware.php`
Kann es sein das dadurch die App nicht funktioniert?
Wenn ich auf Kanalinformation klicke kommt ein langer Code.
![screenshot_2016-10-09-18-45-03](https://cloud.githubusercontent.com/assets/18073299/19222085/a8fcc6a4-8e50-11e6-8c00-8e51373a79f6.png)

**Comment by SirkoVZ** [comment]
eigentlich sollte das kein Problem sein, aber probier mal bitte diese Version...
[volkszaehlerapp_089pre.apk.zip](https://github.com/volkszaehler/app-android/files/522370/volkszaehlerapp_089pre.apk.zip)

**Comment by TylonHH** [comment]
Jupp, mit dieser Version klappt es.
