### ISSUE TITLE
Text unsichtbar + falsche Hintergrundfarbe

### ISSUE THREAD

**Issue by Crazyachmed** [volkszaehler/app-android#21]
Hi

Ich glaube es hat mit dem Update auf Android 6 begonnen, aber seitdem ist der Text im Infopopup zum Graphen unsichtbar (schwarz auf schwarz)

![screenshot_20170128-205503](https://cloud.githubusercontent.com/assets/8402464/22399424/9bfb3a14-e59c-11e6-9b6a-80db22c83d4c.png)

Außerdem ist der Hintergrund in der Übersicht und im Graphen jetzt weiß anstatt schwarz, hat evtl. etwas damit zu tun (oder ist das Absicht?)

![screenshot_20170128-205442](https://cloud.githubusercontent.com/assets/8402464/22399426/9bfc54da-e59c-11e6-8082-3390c03e91cd.png)
![screenshot_20170128-205457](https://cloud.githubusercontent.com/assets/8402464/22399425/9bfbc88a-e59c-11e6-907a-c627db785c9b.png)

Bei mir läuft CM14.1/LineageOS/Android 7.1.1

Gruß,
Flo

**Comment by TylonHH** [comment]
Welche Version der VZ App nutzt du? Aktuell ist 0.9.0
Bei mir sieht alles gut aus.
![screenshot_2017-01-29-09-06-54](https://cloud.githubusercontent.com/assets/18073299/22402755/a12ed016-e602-11e6-99ac-eacdb26c5a15.png)
![screenshot_2017-01-29-09-06-44](https://cloud.githubusercontent.com/assets/18073299/22402756/a93e1c4e-e602-11e6-96a0-1d2b0f0470ad.png)

**Comment by Crazyachmed** [comment]
Auch die 0.9.0. Wenn ich mich richtig erinnere hat das mit dem Android 5.1 nach 6.0 Update begonnen. Auf meinem 7.1.1er ROM jetzt ist keine Theme-Engine integriert.

**Comment by Crazyachmed** [comment]
Habe die App jetzt auf einem Nexus 10 installiert mit 7.1.1 (OmniRom). Das habe ich auch letzte Woche komplett platt gemacht. Sieht genauso (kaputt) aus, wie auf meinem Handy.

Was hast du für eine Android Version?

**Comment by SirkoVZ** [comment]
Ich kann das im Emulator nachvollziehen. Ich schau's mir mal an, danke für den Hinweis.

**Comment by SirkoVZ** [comment]
fixed in https://github.com/volkszaehler/app-android/releases/tag/0.9.1

**Comment by Crazyachmed** [comment]
Läuft, danke!

**Comment by SirkoVZ** [comment]
gefixt
