### ISSUE TITLE
Add a license to this project

### ISSUE THREAD

**Issue by l3d00m** [volkszaehler/app-android#25]
At the current state, this project has no license. Means theoretically nobody is a allowed to modify nor use the code in any kind of way. 

It would be great if you could [add a license](https://help.github.com/articles/adding-a-license-to-a-repository/) to the project so I know what I'm allowed to do, as I'm currently looking into rewriting the code :)

**Comment by SirkoVZ** [comment]
which license do you suggest?
Licensed under the GNU Public License (http://opensource.org/licenses/gpl-license.php).
as https://github.com/volkszaehler/volkszaehler.org?

**Comment by andig** [comment]
MIT would be more permissive

Viele Grüße,
Andreas

**Comment by l3d00m** [comment]
I personally like if the modified code has to stay open source which GPL(v3) requires. [Here's a small overview](https://choosealicense.com/licenses/). There are people who prefer MIT though, as it allows nearly everything as long as your name is stated.  
I'm very new to the FOSS "scene" so I can't really comprehend the disadvantages and advantages of each license.

I think you have to both agree on the license as you both contributed, not too sure though,

Lg

**Comment by andig** [comment]
Imho its all Sirko's code so hebcsn decide which goals to pursue. It would be in the spirit of vz to stay with GPL I have to concede...

Viele Grüße,
Andreas

**Comment by mbehr1** [comment]
I'd prefer v2 and not v3. 

Gruß
Matthias 

Sent from a mobile device.

**Comment by SirkoVZ** [comment]
I'll add the same license as we have for folkszaehler.org
GNU GENERAL PUBLIC LICENSE
Version 3, 29 June 2007

**Comment by SirkoVZ** [comment]
...added
