### ISSUE TITLE
Last release lacks APK

### ISSUE THREAD

**Issue by IzzySoft** [volkszaehler/app-android#27]
For v0.9.2, there's no `.apk` attached in `releases/`. Could you please fill that gap? Thanks in advance!

PS: Please also take a look at [this](https://www.virustotal.com/de/file/0cb1ab548613964e31f02dd97142c865cf1cccd5c898541152777cfb4fde5d56/analysis/1490020394/). You probably can ignore WhiteArmor (that scanner always finds some "PUA", ie. Potentially Unwanted Addon), but I'm not sure about the other one. Not my upload, but VT matched that hash.

**Comment by SirkoVZ** [comment]
Hi,

the upload was not possible, somtimes there are issues uploading files 
on Github.
However, now I managed it... :-)

I scanned the last releasse 0.9.2, only WhiteAmor says: 
PUP.HighConfidence now.

Regards
Sirko


Am 30.06.2017 um 20:49 schrieb Izzy:

**Comment by SirkoVZ** [comment]
Upload successfull

**Comment by IzzySoft** [comment]
Thanks! And confirmed. At VT, I tend to ignore WhiteArmor – they are far too sensible. Still being curious: Any idea what they could mean by that "PUP.HighConfidence"? I mean, PUP is "Potential Unwanted Program" – but what makes them think that? HighConfidence might point to the "BUT the certificate is not really checked, the app accepts also invalid or Man-in-the-Middle certificates" I guess, if that's so obvious an automated scan of the `.apk` would reveal it (any reason why you made it that way?)

**Comment by SirkoVZ** [comment]
I don't think that they do a code analysis to see that all certificates are accepted, I guess it is just a "false positive"

**Comment by IzzySoft** [comment]
Wouldn't surprise me. About every second app is declared PUA/PUP by WhiteArmor, so I honestly cannot take them that seriously somehow (I personally tend to ignore them meanwhile because of that). Still, I never was able to prove the one or the other, as their declaration doesn't give details on what they refer to. Those cryptic names don't give a clue, and searching them doesn't bring up anything enlightening either. So if you have no idea, I'd say "false positive" is the most likely answer here.

Thanks again for caring!
