### ISSUE TITLE
Sortierung der Kanäle

### ISSUE THREAD

**Issue by themanfrommoon** [volkszaehler/app-android#29]
Hallo Sirko,

vielen Dank für die Änderung!
Ich habe aber eine kleine Weile gebraucht, um zu verstehen wie die Sortierung sortiert.
Zuerst habe ich gedacht, dass es nicht funktioniert.
Bis ich verstanden habe, dass die Sortierung der Gruppen alphabetisch und innerhalb der Gruppe ebenfalls alphabetisch ist.
Ja, das ist nachvollziehbar und sicher auch von machen Usern so gewollt :-)

Ich hatte allerdings mit einer anderen Sortierung gerechnet.
In meiner Vorstellung sollte das etwas anders aussehen, und zwar ohne die Gruppierung.
Es sollten alle Kanäle und alle Gruppen untereinander stehen.
So kann man dann direkt auf die einzelnen Kanäle als auch auf die Gruppen zugreifen.

Vielleicht kannst du noch eine Checkbox einführen, mit der man in der Kanalliste die Gruppierung ein und ausschalten kann. Also wahlweise so sortiert wie es jetzt ist oder alle Kanäle und Gruppen alphabetisch hintereinander weg.
Ich denke beides hat seinen Charme.

Vielen Dank nochmal für deine Arbeit!
Lieben Gruß,
Chris

**Comment by SirkoVZ** [comment]
sollte gefixt sein, bitt testen
https://github.com/volkszaehler/app-android/releases/tag/v.0.9.4

**Comment by themanfrommoon** [comment]
Hallo Sirko,

funktioniert perfekt!
Das ist eine sehr deutliche Komfortsteigerung in der Benutzung!
Vielen Dank!

Wie kann ich dir eigentlich ohne einen "Issue" aufzumachen eine Nachricht schreiben?
Ich hab da noch ein paar Ideen.

Lieben Gruß,
Chris
