### ISSUE TITLE
Sortierung der Kanäle im Kontextmenü

### ISSUE THREAD

**Issue by themanfrommoon** [volkszaehler/app-android#30]
Hallo Sirko,

ich habe nochmal etwas mehr getestet.
Wenn ein Diagramm angezeigt wird, kann man ja mit einem langen Klick ein Kontextmenu öffnen und weitere Kanäle dem Diagramm hinzufügen.
Auch hier wäre die gleiche Sortierlogik wünschenswert (wieder mit und ohne Gruppierung, gleiche Checkbox, also eine Sortierlogik für beide Listen, nicht jede separat)

Lieben Gruß,
Chris

**Comment by SirkoVZ** [comment]
sollte auch gefixt sein, bitt testen nur ohne Gruppierung
https://github.com/volkszaehler/app-android/releases/tag/v.0.9.4

**Comment by themanfrommoon** [comment]
Hallo Sirko,

funktioniert perfekt!
Das ist eine sehr deutliche Komfortsteigerung in der Benutzung!
Vielen Dank!

Wie kann ich dir eigentlich ohne einen "Issue" aufzumachen eine Nachricht schreiben?
Ich hab da noch ein paar Ideen.

Lieben Gruß,
Chris
