### ISSUE TITLE
Kanalcheckboxen

### ISSUE THREAD

**Issue by themanfrommoon** [volkszaehler/app-android#32]
Hallo Sirko,

Super Arbeit, das muss ich erst mal loben!

Ich hätte dennoch eine kleine Verbesserungsidee.
Ich habe aktuell 44 Kanäle.
Jedes Mal wenn ich die Kanäle abrufe, muss ich jeden Kanal einzeln aktivieren.
Für meinen Geschmack würde ich standardmäßig nach dem abrufen alle Kanäle aktivieren (und nicht wie aktuell alle Kanäle deaktiviert nach dem Abrufen).
Und/oder eine Checkbox um alle gleichzeitig du aktivieren/deaktivieren.
Das spart nochmal ne Menge Arbeit beim Benutzen und erhöht nochmal deutlich den Bedienkomfort.

Wie kann ich dir eigentlich ohne einen "Issue" aufzumachen eine Nachricht schreiben?
Ich hab da noch ein paar Ideen. Aber vielleicht sollte man da erst mal drüber schreiben ohne direkt einen neuen Issue aufzumachen.

Lieben Gruß,
Chris

**Comment by SirkoVZ** [comment]
eigentlich werden jetzt die ausgewählten Checkboxen erhalten, wenn man die Channels neu runerlädt.
Ich hab aber in der 0.9.5 jetzt standardmäßig alle gecheckt, wenn man die Channel das allererste mal runterlädt

**Comment by SirkoVZ** [comment]
Kontakt: mail_ist@nurfuerspam.de
