### ISSUE TITLE
Performance für Gesamtverbrauch erhöhen

### ISSUE THREAD

**Issue by andig** [volkszaehler/app-android#35]
Im Forum unter https://www.photovoltaikforum.com/volkszaehler-org-f131/vz-simple-frontend-aktueller-wert-t120690.html kam der Hinweis dass die App deutlich länger für Gesamtverbrauch benötigt als das Frontend.

Falls noch nicht implementiert kannst Du mal versuchen `&group=day` and die Abfrage anzuhängen um die Nutzung der Aggregationstabelle zu erzwingen? Das geht schneller weil da deutlich weniger Daten drin stehen...

Viele Grüße, Andreas

**Comment by SirkoVZ** [comment]
ja, das ist schon so, grad nochmal getestet:
http://<ip>/data/<uuid>.json?from=0&tuples=1&group=day

**Comment by andig** [comment]
Komisch- dann verstehe ich nicht warum die App langsamer als das Frontend sein sollte. Wenn Du magst gerne im PV Forum nachhaken, sonst können wir das Thema gerne zu machen.

**Comment by SirkoVZ** [comment]
hmm, interessant wäre zu wissen, an welcher Stelle genau die Abfrage 1 min dauert soll...

**Comment by SirkoVZ** [comment]
group=day bereits eingeschaltet
