### ISSUE TITLE
Kosten werden in Listenansicht bei 'water' nicht angezeigt

### ISSUE THREAD

**Issue by princemichi** [volkszaehler/app-android#36]
Hallo,
beim Wasserverbrauch werden die Kosten in der Listenansicht nicht angezeigt, obwohl die Kosten eigentlich hinterlegt sind!

**Comment by SirkoVZ** [comment]
gefixt in 0.9.6

**Comment by princemichi** [comment]
Super Klasse! Funktioniert, vielen Dank :-)
