### ISSUE TITLE
backup & restore does not work

### ISSUE THREAD

**Issue by git-olicat** [volkszaehler/app-android#38]
Hi!

I'm unable to backup my settings in VolkszaehlerApp 0.9.6:

**"Fehler beim Speichern der Einstellungen!"**

Also I can not restore a backup from another smartphone:

**"Fehler beim Wiederherstellen der Einstellungen!"**

Probably the app does not find the right location for save&restore.

If I interpret the source correctly, the app tries to write to the external memory or to read from there.
But my smartphone has only internal memory!
Maybe it would be advisable to check beforehand if there is an external memory and if not, to use the internal memory? Or even make the storage path configurable?

It apparently affects the functions saveFile and loadFile in Tools.java.

BQ Aquaris X Pro
Android v7.1.1

Regards, Oliver

**Comment by princemichi** [comment]
Hello,
i have the same error at 0.9.6 with Samsung S8 but this works also not with 0.9.5!
Sorry had not the time to repot this in the past.
Thanks,
Michael

**Comment by SirkoVZ** [comment]
Hi,

 

könnt ihr die Version mal versuchen? (alte ggfs. deinstallieren)

 

Danke

Sirko

Gesendet: Donnerstag, 14. Dezember 2017 um 16:27 Uhr
Von: "P.M." <notifications@github.com>
An: volkszaehler/app-android <app-android@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [volkszaehler/app-android] backup & restore does not work (#38)


Hello,
i have the same error at 0.9.6 with Samsung S8 but this works also not with 0.9.5!
Sorry had not the time to repot this in the past.
Thanks,
Michael

**Comment by git-olicat** [comment]
Hi Sirko,

> könnt ihr die Version mal versuchen? (alte ggfs. deinstallieren)
welche Version? Irgendwie fehlt mir da ein Link?
;-)
Gruesse, Oliver

**Comment by SirkoVZ** [comment]
ab Android 6 muß die App explizit fragen, ob die Permissions erlaubt werden sollen. DAs ist jetzt drin, Backup und Restore sollten jetzt funktionieren.
https://github.com/volkszaehler/app-android/releases/latest

**Comment by princemichi** [comment]
Tested: Works.
Thanks!
