### ISSUE TITLE
Add user/password authentication

### ISSUE THREAD

**Issue by princemichi** [volkszaehler/app-android#43]
Hello,

i have tested the auth-functionallty from andig https://github.com/volkszaehler/volkszaehler.org/pull/659
But the app doesn´t work when i setup the middleware for auth.

Can you help me?
Thanks!

**Comment by andig** [comment]
> doesn´t work 

That's pretty broad. I assume you're connecting from a network that doesn't have read access unless using user/password?

Authentication still needs to be implemented for the app. Otherwise simply allow GET from all networks for time being.

**Comment by princemichi** [comment]
Yes. I have selected allow at the moment.
And yes. it was clear to me, that this function was not implemented yet ...
